import { test, expect, Page } from '@playwright/test';

/**
 * ServiceNow Developer Portal — Sign In and navigation.
 *
 * Generated by the 🎭 planner/generator agents from
 * specs/servicenow-navigation.md, using selectors verified against the live site.
 *
 * Credentials come from the local .env file (loaded by playwright.config.ts):
 *   SERVICENOW_USERNAME, SERVICENOW_PASSWORD
 */

const username = process.env.SERVICENOW_USERNAME ?? '';
const password = process.env.SERVICENOW_PASSWORD ?? '';

/** Dismiss the cookie consent banner if it is present. */
async function dismissCookieBanner(page: Page): Promise<void> {
  const accept = page.getByRole('button', { name: 'Accept and Proceed' });
  if (await accept.isVisible().catch(() => false)) {
    await accept.click();
  }
}

/** Drive the two-step ServiceNow ID login form on signon.servicenow.com. */
async function signIn(page: Page, email: string, pwd: string): Promise<void> {
  // Homepage Sign In button redirects to signon.servicenow.com
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.waitForURL(/signon\.servicenow\.com/, { timeout: 30_000 });

  // Step 1: email + Next
  const emailField = page.getByRole('textbox', { name: 'Email' });
  await expect(emailField).toBeVisible({ timeout: 30_000 });
  await emailField.fill(email);
  await page.getByRole('button', { name: 'Next' }).click();

  // Step 2: password (revealed on the same page) + Sign in
  const passwordField = page.getByRole('textbox', { name: 'Password' });
  await expect(passwordField).toBeVisible({ timeout: 30_000 });
  await passwordField.fill(pwd);
  await page.getByRole('button', { name: 'Sign in' }).click();
}

test.describe('ServiceNow Developer Portal', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('https://developer.servicenow.com/dev.do');
    await dismissCookieBanner(page);
  });

  test('signs in successfully', async ({ page }) => {
    test.skip(!username || !password, 'SERVICENOW_USERNAME / SERVICENOW_PASSWORD not set in .env');

    await signIn(page, username, password);

    // On success we are redirected back to the developer portal...
    await page.waitForURL(/developer\.servicenow\.com\/dev\.do/, { timeout: 60_000 });

    // ...and the Sign In button is replaced by the User Profile menuitem.
    await expect(page.getByRole('menuitem', { name: 'User Profile' })).toBeVisible({ timeout: 30_000 });
    await expect(page.getByText(/invalid username or password/i)).toHaveCount(0);
  });

  test('shows an error for invalid credentials', async ({ page }) => {
    // Homepage Sign In button redirects to signon.servicenow.com
    await page.getByRole('button', { name: 'Sign In' }).click();
    await page.waitForURL(/signon\.servicenow\.com/, { timeout: 30_000 });

    // Enter an unknown email and continue. ServiceNow validates the account at
    // the email step, so the error may appear here OR after a password attempt.
    const emailField = page.getByRole('textbox', { name: 'Email' });
    await expect(emailField).toBeVisible({ timeout: 30_000 });
    await emailField.fill('invalid-user@example.com');
    await page.getByRole('button', { name: 'Next' }).click();

    // If a password field is revealed, submit a wrong password too.
    const passwordField = page.getByRole('textbox', { name: 'Password' });
    if (await passwordField.isVisible({ timeout: 5_000 }).catch(() => false)) {
      await passwordField.fill('wrong-password');
      await page.getByRole('button', { name: 'Sign in' }).click();
    }

    // Either way we must stay on the sign-on page and see an error.
    await expect(page).toHaveURL(/signon\.servicenow\.com/, { timeout: 15_000 });
    await expect(
      page.getByText(/invalid|incorrect|not found|does not match|couldn'?t (sign|log)|no account/i).first()
    ).toBeVisible({ timeout: 30_000 });
  });

  // The Industries entry is a hover-activated mega-menu rendered inside a web
  // component (shadow DOM). Its flyout links (e.g. Automotive) are lazy-loaded
  // only on a genuine pointer hover, and on the authenticated home page a
  // `dps-home-auth-quebec` element overlaps the header and intercepts events.
  // Synthetic/forced interactions do not reliably open it, so this scenario is
  // parked for the 🎭 healer to repair interactively against the live DOM.
  test.fixme('opens the Industries mega-menu after signing in', async ({ page }) => {
    await signIn(page, username, password);
    await page.waitForURL(/developer\.servicenow\.com\/dev\.do/, { timeout: 60_000 });
    await expect(page.getByRole('menuitem', { name: 'User Profile' })).toBeVisible({ timeout: 30_000 });

    const industries = page.getByRole('button', { name: 'Industries' });
    await industries.hover({ force: true });

    await expect(page.getByRole('link', { name: /automotive/i }).first())
      .toBeVisible({ timeout: 15_000 });
  });
});
